"""
appreciation.py — XGBoost future valuation inference.


Inference pipeline
------------------
1. Fetch live FRED macro data (mortgage_rate, fed_funds, unemployment, CPI)
2. Build a 29-element feature vector from listing fields + macros
3. Impute numeric NaNs with training medians (from preprocess_meta.json)
4. One-hot encode categoricals (unknown values → all-zeros row)
5. Run model for 3 horizons (6 / 12 / 36 months) × 3 scenarios (best / avg / worst)
  - Scenarios are generated by perturbing macro inputs; the model itself is called once
    per (horizon, scenario) pair — it is a single model, not three separate ones.


FRED series used
----------------
 mortgage_rate  → MORTGAGE30US  (30-year fixed, weekly)
 fed_funds      → FEDFUNDS      (effective rate, monthly)
 unemployment   → UNRATE        (unemployment rate, monthly)
 CPI            → CPIAUCSL      (Consumer Price Index, monthly)
"""
from __future__ import annotations


import json
from pathlib import Path
from typing import Optional


import httpx


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


_MODELS_DIR = Path(__file__).parent.parent / "models"


# ---------------------------------------------------------------------------
# Scenario macro perturbations (deltas added to live FRED values)
# ---------------------------------------------------------------------------


_SCENARIO_DELTAS: dict[str, dict[str, float]] = {
   "best":  {"mortgage_rate": -1.5, "fed_funds": -1.0, "unemployment": -1.5},
   "avg":   {"mortgage_rate":  0.0, "fed_funds":  0.0, "unemployment":  0.0},
   "worst": {"mortgage_rate": +2.0, "fed_funds": +1.5, "unemployment": +2.0},
}


# FRED series IDs for each macro field
_FRED_SERIES: dict[str, str] = {
   "mortgage_rate": "MORTGAGE30US",
   "fed_funds":     "FEDFUNDS",
   "unemployment":  "UNRATE",
   "CPI":           "CPIAUCSL",
}


_FRED_BASE = "https://api.stlouisfed.org/fred/series/observations"


# Property type values from Redfin → training categories
_PROP_TYPE_MAP: dict[str, str] = {
   "sfr":                       "SFR",
   "house":                     "SFR",
   "single family residential": "SFR",
   "single-family residential": "SFR",
   "single family":             "SFR",
   "condo":                     "CONDOMINIUM",
   "condominium":               "CONDOMINIUM",
}




# ---------------------------------------------------------------------------
# Startup: load model + preprocessing metadata
# ---------------------------------------------------------------------------


def load_model_artifacts():
   """
   Load the XGBoost model (joblib) and preprocessing metadata (JSON).
   Call once at application startup and store on app.state.
   Returns (model, meta_dict).
   """
   import joblib  # imported here to keep the module importable without joblib installed


   model = joblib.load(_MODELS_DIR / "appreciation_xgb.joblib")
   with open(_MODELS_DIR / "preprocess_meta.json") as f:
       meta = json.load(f)
   return model, meta




# ---------------------------------------------------------------------------
# FRED: fetch live macro values
# ---------------------------------------------------------------------------


async def fetch_fred_macros(api_key: str) -> dict[str, Optional[float]]:
   """
   Fetch the most recent observation for each FRED series.
   Returns a dict with keys: mortgage_rate, fed_funds, unemployment, CPI.
   Any series that fails returns None (caller falls back to training median).
   """
   results: dict[str, Optional[float]] = {k: None for k in _FRED_SERIES}


   async with httpx.AsyncClient(timeout=httpx.Timeout(10.0)) as client:
       for field, series_id in _FRED_SERIES.items():
           try:
               resp = await client.get(
                   _FRED_BASE,
                   params={
                       "series_id":   series_id,
                       "api_key":     api_key,
                       "file_type":   "json",
                       "sort_order":  "desc",
                       "limit":       1,
                   },
               )
               resp.raise_for_status()
               obs = resp.json().get("observations", [])
               if obs and obs[0]["value"] not in (".", ""):
                   results[field] = float(obs[0]["value"])
           except Exception:
               pass  # stays None; caller uses training median


   return results




# ---------------------------------------------------------------------------
# Feature vector construction
# ---------------------------------------------------------------------------


def _resolve_macro(
   macros: dict[str, Optional[float]],
   field: str,
   meta: dict,
) -> float:
   """Return live macro value, falling back to training median if unavailable."""
   val = macros.get(field)
   if val is not None:
       return val
   idx = meta["num_cols"].index(field)
   return float(meta["num_imputer_medians"][idx])




def _build_feature_vector(
   listing: dict,
   macros: dict[str, Optional[float]],
   meta: dict,
   horizon_months: int,
) -> list[float]:
   """
   Build the 29-element feature vector in the exact feature_names order
   recorded in preprocess_meta.json.


   listing fields consumed
   -----------------------
     price          → baseline_sale_price
     sqft           → living_area_sqft
     bedrooms       → bedrooms
     bathrooms      → bathrooms
     yearBuilt      → year_built
     propertyType   → property_type  (mapped via _PROP_TYPE_MAP)
     garage         → garage_spaces  (True→"Garage, Attached", False→"No Garage", None→"nan")
     pool           → pool_flag      (bool → 0/1)
     zip, state     → zip, state     (OHE; unknown → all-zeros)
     county         → county         (OHE; almost always all-zeros for OC ZIPs)
     latitude       → latitude       (optional; median-imputed if missing)
     longitude      → longitude      (optional; median-imputed if missing)
     lot_size_sqft  → lot_size_sqft  (optional; median-imputed if missing)
     stories        → stories        (optional; median-imputed if missing)
   """
   num_cols = meta["num_cols"]
   cat_cols = meta["cat_cols"]
   medians  = meta["num_imputer_medians"]
   ohe_cats = meta["ohe_categories"]


   # ------------------------------------------------------------------
   # 1. Numeric values — impute None/missing with training median
   # ------------------------------------------------------------------
   raw_numeric: dict[str, Optional[float]] = {
       "horizon_months":      horizon_months,
       "baseline_sale_price": listing.get("price"),
       "living_area_sqft":    listing.get("sqft"),
       "lot_size_sqft":       listing.get("lot_size_sqft"),
       "bedrooms":            listing.get("bedrooms"),
       "bathrooms":           listing.get("bathrooms"),
       "year_built":          listing.get("yearBuilt"),
       "stories":             listing.get("stories"),
       "pool_flag":           1.0 if listing.get("pool") else 0.0,
       "latitude":            listing.get("latitude"),
       "longitude":           listing.get("longitude"),
       "mortgage_rate":       _resolve_macro(macros, "mortgage_rate", meta),
       "fed_funds":           _resolve_macro(macros, "fed_funds",     meta),
       "unemployment":        _resolve_macro(macros, "unemployment",  meta),
       "CPI":                 _resolve_macro(macros, "CPI",           meta),
   }


   numeric_values: list[float] = []
   for i, col in enumerate(num_cols):
       val = raw_numeric.get(col)
       numeric_values.append(float(val) if val is not None else float(medians[i]))


   # ------------------------------------------------------------------
   # 2. Categorical values → OHE
   # ------------------------------------------------------------------
   prop_type_raw = (listing.get("propertyType") or "").lower().strip()
   prop_type = _PROP_TYPE_MAP.get(prop_type_raw, listing.get("propertyType") or "")


   garage_raw = listing.get("garage")
   if garage_raw is True:
       garage_str = "Garage, Attached"
   elif garage_raw is False:
       garage_str = "No Garage"
   else:
       garage_str = "nan"


   raw_cat: dict[str, str] = {
       "property_type": prop_type,
       "zip":           str(listing.get("zip") or ""),
       "county":        str(listing.get("county") or ""),
       "state":         str(listing.get("state") or ""),
       "garage_spaces": garage_str,
   }


   ohe_values: list[float] = []
   for col in cat_cols:
       categories = ohe_cats[col]
       val = raw_cat.get(col, "")
       for cat in categories:
           ohe_values.append(1.0 if val == cat else 0.0)


   # ------------------------------------------------------------------
   # 3. Concatenate — numeric first, then OHE, matching feature_names order
   # ------------------------------------------------------------------
   vector = numeric_values + ohe_values


   expected = len(meta["feature_names"])
   if len(vector) != expected:
       raise ValueError(
           f"Feature vector length {len(vector)} does not match "
           f"expected {expected} from preprocess_meta.json"
       )


   return vector




# ---------------------------------------------------------------------------
# Main inference: 3 horizons × 3 scenarios
# ---------------------------------------------------------------------------


def predict_scenarios(
   listing: dict,
   macros: dict[str, Optional[float]],
   model,
   meta: dict,
) -> list[dict]:
   """
   Run appreciation predictions for every (horizon, scenario) combination.


   Returns a list of dicts shaped as HorizonProjection:
       [
         {
           "months": 6,
           "best":  {"appreciation_pct": 3.2, "projected_value": 825600},
           "avg":   {"appreciation_pct": 1.8, "projected_value": 814400},
           "worst": {"appreciation_pct": -0.5, "projected_value": 796000},
         },
         ... (12 months, 36 months)
       ]
   """
   base_price: Optional[float] = listing.get("price")
   results: list[dict] = []


   for horizon in (6, 12, 36):
       horizon_result: dict = {"months": horizon}


       for scenario, deltas in _SCENARIO_DELTAS.items():
           # Perturb macro inputs; CPI is held constant across scenarios
           perturbed: dict[str, float] = {
               "mortgage_rate": _resolve_macro(macros, "mortgage_rate", meta) + deltas["mortgage_rate"],
               "fed_funds":     _resolve_macro(macros, "fed_funds",     meta) + deltas["fed_funds"],
               "unemployment":  _resolve_macro(macros, "unemployment",  meta) + deltas["unemployment"],
               "CPI":           _resolve_macro(macros, "CPI",           meta),
           }


           vec = _build_feature_vector(listing, perturbed, meta, horizon)
           appreciation_pct = float(model.predict([vec])[0])


           projected_value: Optional[int] = (
               round(base_price * (1.0 + appreciation_pct / 100.0))
               if base_price else None
           )


           horizon_result[scenario] = {
               "appreciation_pct": round(appreciation_pct, 2),
               "projected_value":  projected_value,
           }


       results.append(horizon_result)


   return results



